version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "yarn install && yarn start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
